version: 2
updates:
  - package-ecosystem: nuget
    directory: "/MaLoIdentModels"
    schedule:
      interval: "weekly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
